### ISSUE TITLE
Request for a new plugin: 1plus1 calculator

### ISSUE THREAD

**Issue by GianricoT** [E2OpenPlugins/e2openplugin-TelekomSport#1]
Hi Betacentauri, 

First off I would like to apologize for highjacking the Issues tab of this project (TelekomSport), but I didn't know how else to submit a request for a new plugin to be incorporated in the E2OpenPlugins project.  You seem to be an active developer of the project, so I thought you might be interested.

I have put together a simple arithmetic calculator plugin for enigma2, called _1plus1_

Feel free to fork/share/test/copy/edit it, or even to package it for distribution along with the other E2 OpenPlugins.   If you like the plugin, simply clone it in your github account and use it/distribute it as yours.

Its webpage is [https://gitlab.com/GianricoT/1plus1](https://gitlab.com/GianricoT/1plus1) and the source code lives at [https://gitlab.com/GianricoT/1plus1.git](https://gitlab.com/GianricoT/1plus1.git)

**Comment by WanWizard** [comment]
I have created e2openplugin-1plus1 and made you admin. You should have received an invitation.

**Comment by GianricoT** [comment]
Got it, thanks WanWizard !  

The e2openplugin-1plus1 github repo has been populated and its content should be ready for consumption.
 Feel free to test it my plugin.

**Comment by betacentauri** [comment]
Has nothing to do with the plugin -> close
